import type { Metadata } from "next";
import "./globals.css";
import "../styles/global.css";
import { ThemeProvider } from "@/components/DarkMode/theme-provider";
import { allFonts } from "./fonts";
import { Footer7 } from "@/components/footer/footer-7";
import HeroHeader from "@/components/header/Header1";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${allFonts} font-neutral`}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <HeroHeader />
          {children}
          <Footer7 />
        </ThemeProvider>
      </body>
    </html>
  );
}
